### ISSUE TITLE
Create a mockup for the settings page (backend) and for the example page (frontend)

### ISSUE THREAD

**Issue by PSahner** [resmio/wp-resmio-api#21]
Fabi will create some mockups for the backend and frontend as soon as she finds time to do it. Should be in 2 weeks or so.
@fabiennepimenta Just come to me when you have time so we can discuss the issue.

**Comment by fabiennepimenta** [comment]
@PSahner I need access to a Wordpress account with our plugin – otherwise it's not possible to improve it without seeing it ;)

**Comment by fabiennepimenta** [comment]
I made to options for this. 
I've also changed a bit the UX of this page ( different text, different steps ) but of course we can discuss that :) 

Restaurant info before - Widget in the bottom 
![desktop hd](https://cloud.githubusercontent.com/assets/3285116/14680458/ab148478-071d-11e6-9dea-b1d1fbd6fd1b.png)

Widget in the Top - Restaurant info after
![desktop hd copy](https://cloud.githubusercontent.com/assets/3285116/14679962/5d3edbf0-071c-11e6-8f28-b0b885a78c9c.png)

Also have the same versions but with [resmio-something] in black, as the rest of the text (but I think is good to give some emphasis to it).

![desktop hd copy 2](https://cloud.githubusercontent.com/assets/3285116/14680493/c22a54e4-071d-11e6-9107-ed0cb43d4a8e.png)

![desktop hd copy2](https://cloud.githubusercontent.com/assets/3285116/14680133/73b86216-071c-11e6-8645-c534cf962b78.png)

**Comment by PSahner** [comment]
First the restaurant info and than widget & button is better I think.
@fabiennepimenta Can you give us the icons as svg or where do we get those?

**Comment by fabiennepimenta** [comment]
If users have more than 3 opening hours set we show all of them. If they just have one, we show the filled one and 2 empty.

For the social icons, I was checking their branding guidelines and I think is better to use with the 'box' and not with outlines (like we had before). 

google drive > design stuff > social icons svg : 

SVG's icons are available in our google drive > design stuff > icons > svg icons: 
Phone: symbol-phone.svg 
Email: symbol-email.svg

Mobile version: 
![mobile portrait](https://cloud.githubusercontent.com/assets/3285116/14707855/2eec9426-07c7-11e6-98cc-06d906a63155.png)
